language: php

services:
  - mysql

php:
  - 7.1
  - 7.2
  
before_script:
  # Set application parameters ...
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  # Composer install ...
  - travis_retry composer install --no-interaction
  # Remove application cache and logs ...
  - rm -Rf var/cache/*
  - rm -Rf var/logs/*
  # Prepare application cache ...
  - php bin/console cache:warm --env=test
  - php bin/console cache:warm --env=dev
  # Grant application cache and logs permissions ...
  - chmod -Rf 777 var/cache/
  - chmod -Rf 777 var/logs/
  # Create application database ...
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  

script:
  - ./vendor/bin/phpunit --colors --configuration ./phpunit.xml.dist tests
  - ./vendor/bin/phpstan analyse -c phpstan.neon -l 7 ./src
  - ./vendor/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock