<?php

namespace AppBundle\Uploader;

use Symfony\Component\HttpFoundation\File\File;

/**
 * File uploader interface
 */
interface UploaderInterface
{

    /**
     * Upload file
     *
     * @param File $file
     *
     * @param string|null $fileName Upload with given filename. Filename is randomly generated by default
     *
     * @return string Uploaded file name (with extension)
     */
    public function upload(File $file, string $fileName = null): string;

    /**
     * Get file url
     *
     * @param string $fileName Uploaded file name (with extension)
     *
     * @return string Url
     */
    public function fileUrl(string $fileName): string;

    /**
     * Remove file
     *
     * @param string $fileName Uploaded file name (with extension)
     */
    public function removeFile(string $fileName): void;
}
